### ISSUE TITLE
Setting up the environment on ubutu 19.10

### ISSUE THREAD

**Issue by HackIvan** [PadamSethia/automato#17]
I've been try to download all the perquisite to start the installation, but i still do faces challenge. Please indicate clear steps on how to go about the installation and all the libraries needed for it to work
thanks

**Comment by PadamSethia** [comment]
Can you post the error log . It might be due to the requirements not being installed . I have just added requirements.txt file , install those and let me know if it works out

**Comment by HackIvan** [comment]
(base) amor@Re-bound:~/clones/automato/back$ cd ..
(base) amor@Re-bound:~/clones/automato$ cd front
(base) amor@Re-bound:~/clones/automato/front$ npm run dev 

> front@1.0.0 dev /home/amor/clones/automato/front
> nuxt

sh: 1: nuxt: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! front@1.0.0 dev: `nuxt`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the front@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/amor/.npm/_logs/2020-04-20T21_41_24_715Z-debug.log
(base) amor@Re-bound:~/clones/automato/front$

**Comment by HackIvan** [comment]
[2020-04-20T21_41_24_715Z-debug.log](https://github.com/PadamSethia/automato/files/4506352/2020-04-20T21_41_24_715Z-debug.log)
Here is the error log

**Comment by PadamSethia** [comment]
It seems like the npm modules have't been installed , try installing them by running npm install in the front directory

**Comment by HackIvan** [comment]
ok thanks
let me do

**Comment by HackIvan** [comment]
yeah
Installed 
but telling me now about sql
tryin to fix that

**Comment by HackIvan** [comment]
thanks anyways for the help so far
GOD Bless you

**Comment by PadamSethia** [comment]
What error is it showing for SQL ?

**Comment by HackIvan** [comment]
(base) amor@Re-bound:~/clones/automato/back$ python run.py
Traceback (most recent call last):
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 5, in <module>
    db.create_all()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1033, in create_all
    self._execute_for_all_tables(app, bind, 'create_all')
  File "/home/amor/anaconda3/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 1025, in _execute_for_all_tables
    op(bind=self.get_engine(app, bind), **extra)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
    ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2048, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/home/amor/anaconda3/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2040, in _optional_conn_ctx_manager
    with self._contextual_connect() as conn:
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2280, in _wrap_pool_connect
    e, dialect, self
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
    rec = pool._do_get()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
    self._dec_overflow()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
    return self._create_connection()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
    connection = pool._invoke_creator(self)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 482, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 599, in connect
    self._request_authentication()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 861, in _request_authentication
    auth_packet = self._read_packet()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/connections.py", line 684, in _read_packet
    packet.check_error()
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/protocol.py", line 220, in check_error
    err.raise_mysql_exception(self._data)
  File "/home/amor/anaconda3/lib/python3.7/site-packages/pymysql/err.py", line 109, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'root'@'localhost' (using password: YES)")
(Background on this error at: http://sqlalche.me/e/e3q8)
(base) amor@Re-bound:~/clones/automato/back$

**Comment by HackIvan** [comment]
Can you please add me up on whatsapp if you dont mind?
Thanks
+23276334011

**Comment by PadamSethia** [comment]
The  error says that you have error in your mysql password , please correct that in the config.py file and add the correct password for your mysql db

**Comment by HackIvan** [comment]
Ok
I will do
thanks
